hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
        path: /uaa/**
        url: http://auth-service:5000
        stripPrefix: false
        sensitiveHeaders:

    account:
        path: /accounts/**
        serviceId: account
        stripPrefix: false
        sensitiveHeaders:

    statistics:
        path: /statistics/**
        serviceId: statistics
        stripPrefix: false
        sensitiveHeaders:

    notification:
        path: /notifications/**
        serviceId: notification
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000
